### PR TITLE
Fix redirect on 404 error handlers

### LINKED ISSUE #248: I can't perform a redirect in JEX v3.0
```java
ctx.redirect(encodedUrlPath, HttpStatus.MOVED_PERMANENTLY_301.status());
```

```
Apr 12, 2025 5:14:19 PM io.avaje.jex.core.ExceptionManager unhandledException
SEVERE: Uncaught exception
io.avaje.jex.http.RedirectException: Redirect
	at io.avaje.jex.core.JdkContext.redirect(JdkContext.java:432)
	at <...>
	at io.avaje.jex.core.ExceptionManager.handle(ExceptionManager.java:42)
	at io.avaje.jex.core.ServiceManager.handleException(ServiceManager.java:119)
	at io.avaje.jex.core.RoutingHandler.handle(RoutingHandler.java:39)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:873)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:849)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```

Image

Where `mode` is `null`.

### PR DESCRIPTION
**Pull request by SentryMan**
resolves #248

### CODE REVIEW

File: avaje-jex/src/main/java/io/avaje/jex/core/RoutingHandler.java [hunk 1]
```diff
@@ -36,6 +36,7 @@ public void handle(HttpExchange exchange) {
 
     if (route == null) {
       var ctx = new JdkContext(mgr, exchange, uri, Set.of());
+      ctx.setMode(Mode.EXCHANGE);
```
Comment (rbygrave) [inline avaje-jex/src/main/java/io/avaje/jex/core/RoutingHandler.java:39]: I think we can move this into the constructor. Will merge this in but look to adjust later.

**Review by rbygrave — APPROVED** [review]
